config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    
    resources :products do
      resources :stocks
    end
    resources :categories
    # root to: "admin#index"
  end
  resources :members

  # get 'members/index'
  # get 'members/create'
  # get 'members/new'
  # get 'members/edit'
  # get 'members/update'
  # get 'members/destroy'
  resources :companies
   get 'company' => 'companies#index'
  devise_for :users # , :controllers => {:registrations => "users/registrations"}
  resources :friends
  
  get 'home/index', as: :home
  get 'home/about'
  get "admin" => "admin#index"
  get "cashier" => "cashier#index"
  get "manager" => "manager#index"
  get "cart"  => "carts#show"
  #get "invoice"  => "carts#invoice"
  get "categories" => "categories#index"
  # get "category" => "category#index"
  resources :categories, only: [:show]
  resources :products, only: [:show]
  # resources :cashier do
  #   get :index, to: 'cashier#index'  # cashier_index_path
  # end

  # resources :manager do
  #   get :index, to: 'manager#index'  # manager_index_path
  # end
  devise_scope :user do
    root to: 'home#index'
    get 'devise/registrations/new', as: :sign_up
  end

  # namespace :admin do
  #   root to: "admin#index"
  # end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "home#index"
  # root "friends#index"

  # authenticated :user do
  #   root to: "admin#index", as: :admin_root
  # end

end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_products
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :set_admin_order, only: %i[ show edit update destroy ]

  # GET /admin/orders or /admin/orders.json
  # def index
  #   @admin_orders = Order.all
  #   @not_fulfilled_orders = Order.where(fulfilled: false).order(created_at: :asc)
  #  @fulfilled_orders = Order.where(fulfilled: true).order(created_at: :asc)
  # end
  def index
    @not_fulfilled_pagy, @not_fulfilled_orders = pagy(Order.where(fulfilled: false).order(created_at: :asc))
    @fulfilled_pagy, @fulfilled_orders = pagy(Order.where(fulfilled: true).order(created_at: :asc), page_param: :page_fulfilled)
  end

  # GET /admin/orders/1 or /admin/orders/1.json
  def show
  end

  # GET /admin/orders/new
  def new
    @admin_order = Order.new
  end

  # GET /admin/orders/1/edit
  def edit
  end

  # POST /admin/orders or /admin/orders.json
  def create
    @admin_order = Order.new(admin_order_params)

    respond_to do |format|
      if @admin_order.save
        format.html { redirect_to admin_order_url(@admin_order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @admin_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/orders/1 or /admin/orders/1.json
  def update
    respond_to do |format|
      if @admin_order.update(admin_order_params)
        format.html { redirect_to admin_order_url(@admin_order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/orders/1 or /admin/orders/1.json
  def destroy
    @admin_order.destroy!

    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_order
      @admin_order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_order_params
      params.require(:order).permit(:customer_email, :fulfilled, :total, :address)
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_with(model: [:admin, admin_order]) do |form| %>
  <% if admin_order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_order.errors.count, "error") %> prohibited this admin_order from being saved:</h2>
      <ul>
        <% admin_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%# <div>
    <%= form.label :customer_email, style: "display: block" %>
  <%# <%= form.text_field :customer_email %>
  <%# </div>  %>
  <%# <div> %>
  <%# <%= form.label :fulfilled, style: "display: block" %>
  <%# <%= form.check_box :fulfilled %>
  <%# </div> %>
  <%# <div> %>
  <%# <%= form.label :total, style: "display: block" %>
  <%# <%= form.number_field :total %>
  <%# </div> %>
  <%# <div> %>
  <%# <%= form.label :address, style: "display: block" %>
  <%# <%= form.text_field :address %>
  <%# </div> %>
  <%# <div> %>
  <%# <%= form.submit %>
  <%# </div> %>
  <div class="main-wrapper" style="display:inline-block">
    <div class="account-content">
      <div class="login-wrapper">
        <div class="login-content">
          <div class="login-userset">
            <div class="form-login" >
              <%= form.text_field :customer_email, rows: 4, placeholder: "Customer Email" %>
            </div>
            <div class="form-login">
              <%= form.label :fulfilled %>
              <%= form.check_box :fulfilled, class: " h-5 w-5" %>
            </div>
            <div class="form-login">
              <%= form.label :total, style: "display: block" %>
              <%= form.number_field :total %>
            </div>
            <div class="form-login" >
              <%= form.text_field :address, rows: 4, placeholder: "Customer Address" %>
            </div>
          </div>
        </div>
        <div class="login-img">
          <!--        <img src="assets/img/login.jpg" alt="img">-->
          <%= image_tag 'order.jpg' %>
        </div>
      </div>
      <div class= "actions" >
        <%= form.submit class: "btn btn-primary", style:"margin-left:35px; display:inline-block;" %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <%# <p>
    <strong>Customer email:</strong>
    <%= order.customer_email %>
  <%# </p> %>
  <%# <p> %>
  <%# <strong>Fulfilled:</strong> %>
  <%# <%= order.fulfilled %>
  <%# </p> %>
  <%# <p> %>
  <%# <strong>Total:</strong> %>
  <%# <%= order.total %>
  <%# </p> %>
  <%# <p> %>
  <%# <strong>Address:</strong> %>
  <%# <%= order.address %>
  <%# </p> %>
  <tr>
    <td> <%= order.id %> </td>
    <td> <%=  link_to "#{order.customer_email} " , [:admin,  order], class: 'text-decoration-underline text-primary' %>
    </td>
    <td> <%= order.fulfilled %></td>
    <td> <%= order.total %></td>
    <td>  <%= order.address %></td>
    <td>
      <% if order.order_products.any? %>
        <strong class="block font-medium mb-1">Products:</strong>
        <% order.order_products.each do |op| %>
          <%= op.product.name %>
          <%= op.size %>
          <%= op.quantity %>
        <% end %>
      <% end %>
    </td>
  </div>

app/views/admin/orders/edit.html.erb
<h1>Editing order</h1>
<%= render "form", admin_order: @admin_order %>
<br>
<div>
  <%= link_to "Show this order", [:admin, @admin_order] , class: "btn btn-info " %> |
  <%= link_to "Back to orders", admin_orders_path , class: "btn btn-secondary "%>
</div>

app/views/admin/orders/index.html.erb
<%# <p style="color: green"><%= notice</p>  %>
<h1 class="fs-1 text-center">Orders</h1>
<%# <div id="admin_orders">
  <% @admin_orders.each do |admin_order| %>
  <%# <%= render admin_order %>
  <%# <p> %>
  <%# <%= link_to "Show this order", admin_order %>
  <%# </p> %>
  <%# <% end %>
  <%# </div> %>
  <%= link_to "New order", new_admin_order_path , class:"btn btn-primary float-end" %>
  <h2 class="fs-2">Unfulfilled Orders</h2>
  <table class="table table-striped table-hover table-bordered" >
    <thead class="table-light">
      <tr>
        <th>Order ID</th>
        <th>Customer Email </th>
        <th>Fulfilled  </th>
        <th>Total  </th>
        <th>Address  </th>
        <th>Orders  </th>
      </tr>
    </thead>
    <tbody>
      <div id="order">
        <% @not_fulfilled_orders.each do |order| %>
          <%= render order %>
        <% end %>
      </tr>
    </div>
  </tbody>
</table>
<%== pagy_nav(@not_fulfilled_pagy) if @not_fulfilled_pagy.pages > 1 %>
<h2 class="fs-2">Fulfilled Orders</h2>
<table class="table table-striped table-hover table-bordered" >
  <thead class="table-light">
    <tr>
      <th>Order ID</th>
      <th>Customer Email </th>
      <th>Fulfilled  </th>
      <th>Total  </th>
      <th>Address  </th>
      <th>Orders  </th>
    </tr>
  </thead>
  <tbody>
    <div id="order">
      <% @fulfilled_orders.each do |order| %>
        <%= render order %>
      <% end %>
    </tr>
  </div>
</tbody>
</table>
<%== pagy_nav(@fulfilled_pagy) if @fulfilled_pagy.pages > 1 %>
<%= link_to "Back to Products", admin_products_path , class:"btn btn-secondary" %>

app/views/admin/orders/new.html.erb
<h1>New order</h1>
<%= render "form", admin_order: @admin_order %>
<br>
<div>
  <%= link_to "Back to orders", admin_orders_path , class: "btn btn-secondary " , style:"margin-left:35px; display:inline-block;"%>
</div>

app/views/admin/orders/show.html.erb
<%# <p style="color: green"><%= notice</p>  %>
<%# <%= render @admin_order %>
<%# <div>
  <%= link_to "Edit this order", edit_admin_order_path(@admin_order) %>
<%# <%= link_to "Back to orders", admin_orders_path %>
<%# <%= button_to "Destroy this order", @admin_order, method: :delete %>
<%# </div>  %>
<div class="jumbotron">
  <div class="card-body">
    <h1 class="display-4">
      <%= @admin_order.customer_email %>
    </h1>
    <p class="lead">
    </p>
    <hr class= "my-4">
  </div>
</div>
<table class="table table-striped table-hover table-bordered" >
  <thead class="table-light">
    <tr>
      <th>Order ID</th>
      <th>Customer Email </th>
      <th>Fulfilled  </th>
      <th>Total  </th>
      <th>Address  </th>
      <th>Orders  </th>
      <%# <th>User Name <%="\u{1F60E}" </th>  %>
    </tr>
  </thead>
  <%= render @admin_order %>
</tr>
</table>
<div style= "display:inline-block";>
  <%= link_to "Edit", edit_admin_order_path( @admin_order), class:"btn btn-primary",style:"margin-top:10px; margin-bottom:10px;display:inline-block;" %>
  <%= link_to "Back", admin_orders_path, class:"btn btn-secondary" ,style:"margin-top:10px; margin-bottom:10px;display:inline-block;" %>
</div>
<div style= "display:inline-block";>
  <%= button_to "Delete", admin_order_path(@admin_order), method: :delete, class:"btn btn-danger", onclick: 'return confirm("Are you sure?");' %>
</div>
<br>
<br>