config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    
    resources :products do
      resources :stocks
    end
    resources :categories
    # root to: "admin#index"
  end
  resources :members

  # get 'members/index'
  # get 'members/create'
  # get 'members/new'
  # get 'members/edit'
  # get 'members/update'
  # get 'members/destroy'
  resources :companies
   get 'company' => 'companies#index'
  devise_for :users # , :controllers => {:registrations => "users/registrations"}
  resources :friends
  
  get 'home/index', as: :home
  get 'home/about'
  get "admin" => "admin#index"
  get "cashier" => "cashier#index"
  get "manager" => "manager#index"
  get "cart"  => "carts#show"
  #get "invoice"  => "carts#invoice"
  get "categories" => "categories#index"
  # get "category" => "category#index"
  resources :categories, only: [:show]
  resources :products, only: [:show]
  # resources :cashier do
  #   get :index, to: 'cashier#index'  # cashier_index_path
  # end

  # resources :manager do
  #   get :index, to: 'manager#index'  # manager_index_path
  # end
  devise_scope :user do
    root to: 'home#index'
    get 'devise/registrations/new', as: :sign_up
  end

  # namespace :admin do
  #   root to: "admin#index"
  # end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "home#index"
  # root "friends#index"

  # authenticated :user do
  #   root to: "admin#index", as: :admin_root
  # end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # @main_categories = Category.take(4)
  
  end

  def about
    @about_me = "Hi! My Name is Asghar Ali"


    if params[:first_number].present? && params[:second_number].present?
      @first_number = params[:first_number].to_i
      @second_number = params[:second_number].to_i
      @result = @first_number + @second_number
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
    def nav_classes
        return "navbar navbar-expand-lg navbar-dark bg-dark fixed-top mb-20" if !user_signed_in?

        if current_user.cashier?
         "navbar navbar-expand-lg navbar-dark bg-primary fixed-top mb-10"
        elsif current_user.manager?
         "navbar navbar-expand-lg navbar-dark bg-success fixed-top mb-10"
        else 
         "navbar navbar-expand-lg navbar-dark bg-dark fixed-top mb-10"
        end             
    end

end

app/views/home/_admin.html.erb
<div class="container-fluid d-flex flex-row ">
  <nav class="  col-md-2 sticky-top bg-dark text-white flex-wrap overflow-auto border-end " style="height: 42rem;">
    <div class="d-flex align-items-center justify-content-center flex-shrink-0 pt-2">
      <%# <h1 class="text-md py-2 font-bold">POS System</h1> %>
      <%= image_tag('logo.jpg', alt: 'About Us Image',style:"max-width: 100%; hight: 133px; width:100px", class: "logo") %>
    </div>
    <div class = "dcenter">
      <ul class="nav nav-pills flex-column mb-auto " style="margin:20px">
        <li >
          <%# <a class="nav-link active" href="#" style="margin-bottom:10px"><i class="fas fa-tachometer-alt"> Dashboard</i></a> %>
          <%= link_to admin_path, class: "block px-1 py-2 hover:rounded hover:bg-gray-700" do %>
            <%#= icon('fa-solid', 'gauge-high', class: 'mr-2') %> <span class=" fas fa-tachometer-alt hidden md:inline-block fs-4"> Dashboard</span>
          <% end %>
        </li>
        <li style="margin-top:10px; margin-bottom:10px">
          <%= link_to "Profile: #{current_user.id} \u{2740}   #{current_user.email} ", edit_user_registration_path, class:"nav-item btn btn-outline-info" %>
        </li>
        <form class="d-flex" style="margin-bottom:10px">
          <button class="btn btn-success"><%= link_to "Role: #{current_user.role.capitalize} \u{1F466}"%></button>
        </form>
        <%= link_to 'Home', home_path, class: "navbar-brand"%>
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path%>
        </li>
        <li class="nav-item">
          <%= link_to members_path, class: "block px-1 py-2 hover:rounded hover:bg-gray-700" do %>
            <span class=" fas fa-users mr-2 hidden md:inline-block "> User Management</span>
          <% end %>
        </li>
        <hr>
        <li >
          <button id="navbar-toggler" style="display: <%= cookies[:open_menu] ? 'block' : 'block' %>;">
            <i class="fas fa-bars"></i> Product Management
          </button>
          <div id="navbar" >
            <ul>
              <li class="nav-item">
                <%# <i class="fas fa-shopping-cart"></i> Products %>
                <%= link_to admin_products_path, class: "block px-1 py-2 hover:rounded hover:bg-gray-700" do %>
                  <span class=" fas fa-shopping-cart mr-2 hidden md:inline-block "> Products</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_categories_path, class: "block px-1 py-2 hover:rounded hover:bg-gray-700" do %>
                  <span class=" fa fa-list mr-2 hidden md:inline-block "> Categories</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_orders_path, class: "block px-1 py-2 hover:rounded hover:bg-gray-700" do %>
                  <span class=" fas fa-truck mr-2 hidden md:inline-block "> Orders</span>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_path, class: "block px-1 py-2 hover:rounded hover:bg-gray-700" do %>
                  <span class=" fas fa-file mr-2 hidden md:inline-block "> Reports</span>
                <% end %>
              </li>
            </ul>
          </div>
        </li>
        <%# <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
      </li> %>
        <hr>
        <li >
          <button id="customer-toggler" style="padding-right:2px;display: <%= cookies[:open_menu] ? 'block' : 'none' %>;">
            <i class="fas fa-bars"></i> Sale Processing
          </button>
          <hr>
          <div id="customer" >
            <ul>
              <li class="nav-item flex space-x-10 pl-5 pr-5">
                <%= link_to 'Sell', categories_path, class: "text-gray-500 py-2 rounded-md text-md font-medium" %>
              </li>
              <li class="nav-item">
                <div class="flex space-x-10">
                  <%= link_to  cart_path, class: "text-gray-500 hover:underline py-2 rounded-md text-md font-medium" do %>
                    <%# <%= icon 'fa-solid', 'shopping-cart' %>
                    <span class = "fas fa-shopping-cart "> Cart</span>
                  <% end %>
                </div>
              </li>
            </ul>
          </div>
        </li>
        <hr>
        <li style="margin:15px">
          <%= button_to "Sign Out", destroy_user_session_path, :method => 'delete', data:{turbo: "false"}, class:"fas fa-sign-out-alt btn btn-primary mt-1 py-1", style: "color: #157347" %>
        </li>
      </ul>
    </div>
  </nav>
  <script>
    // Function to toggle navbar visibility
    let nav = document.querySelector('#navbar-toggler')

    nav.addEventListener('click', function() {
       const toggleButton = document.getElementById('navbar');
       if (toggleButton.style.display === 'none') {
           toggleButton.style.display = 'block';
           document.cookie = "open_menu=false"; // Set cookie to true on open
       } else {
           toggleButton.style.display = 'none';
           document.cookie = "open_menu=true"; // Set cookie to false on close
       }
       });


       // Function to toggle navbar visibility
       document.getElementById('customer-toggler').addEventListener('click', function() {
       const toggleButton = document.getElementById('customer');
       if (toggleButton.style.display === 'none') {
           toggleButton.style.display = 'block';
           document.cookie = "open_menu=true"; // Set cookie to true on open
       } else {
           toggleButton.style.display = 'none';
           document.cookie = "open_menu=false"; // Set cookie to false on close
       }
       });
  </script>

app/views/home/_footer.html.erb
<footer class="bg-gray-800 text-white">
  <div class="max-2-6xl max-auto px-4 py-10 md:py-20">
    <div class="xl:grid xl:grid-cols-3 xl:gap-8">
      <!-- About section -->
      <div class="space-y-8 xl:col-span-1">
        <h3 class="text-sm font-semibold text-gray-200 tracking-wider uppercase">About POS</h3>
        <p class="text-white leading-6">
          POS is a leading online as wel as offline marketplace, offering a wide range of products to cater to all your needs. Our commitment ot quality and customer service ensures a great shopping experience.
        </p>
      </div>
      <!-- Quick Links -->
      <div class="mt-12 grid grid-cols-2 gap-8 xl:mt-0 xl:col-span-2">
        <div class="md:grid md:grid-cols-2 md:gap-8">
          <%# <div>
            <h3 class="text-sm font-semibold text-gray-200 tracking wider uppercase">Quick Links</h3>
            <ul class="mt-4 space-y-4">
              <li>
                <%= link_to "Home", root_path, class: "text-base leading-6 text-white hover:text-gray-100" %>
          <%# </li> %>
          <%# </ul> %>
          <%# </div>  %>
        </div>
      </div>
      <!-- Contact information -->
      <div class="mt-8 mb-8 md:grid md:grid-cols-2 md:gap-8">
        <div>
          <h3 class="text-sm font-semibold tracking-wider uppercase text-gray-200">
            Contact Us
          </h3>
          <ul class="mt-4 space-y-4">
            <li>
              <p class="text-base leading-6 text-white">
                123 POS <br>
                Point of Sale City, ABC 12345
              </p>
            </li>
            <li>
              <p class="text-base leading-6 text-white">
                Email: asghar.ssri.jc@gmail.com
              </p>
            </li>
            <li>
              <p class="text-base leading-6 text-white">
                Phone: (321) 7789336
              </p>
            </li>
          </ul>
        </div>
      </div>
      <div class="border-t border-gray-700">
        <div class="max-w-6xl mx-auto px-4 py-6 md:flex md:items-center md:justify-between">
          <p class="mt-6 text-base leading-6 text-gray-400 md:mt-0 md:order-1">
            &copy; <%= Time.now.year %> POS, Inc. All rights reserved.
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="card text-black">
    <div class="card-header">
      Author: Asghar Ali
    </div>
    <div class="card-body ">
      <h5 class="card-title">Final Year Project</h5>
      <p class="card-text ">This App has been developed under the supervision of <strong>Miss Saima Jamil</strong></p>
      <p class="card-text ">Special Thanks to <strong>Naveed Bhai</strong> for guidance and help</p>
      <div  style= "display:inline-block">
        <% if !user_signed_in? %>
          <%= link_to 'Sign In', new_user_session_path, class:"btn btn-primary"%>
        <% else %>
          <%# <%= link_to 'Sign Out', destroy_user_session_path, method: :delete%>
          <%= button_to "Sign Out", destroy_user_session_path, :method => 'delete', data:{turbo: "false", style: "display:inline-block"}, class:" btn btn-primary" %>
        <% end %>
      </div>
      <div  style= "display:inline-block">
        <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
        <%= link_to 'Go to Home', home_path, class:"btn btn-secondary", style: "display:inline-block" %>
      </div>
    </div>
  </div>
</footer>

app/views/home/_header.html.erb
<% if user_signed_in? && current_user.admin? %>
  <h2 class="fs-1"> POS FOR RETAIL AND SALES MANAGMENT </h2>
<%else%>
  <nav class="<%= nav_classes %>">
    <div class="container-fluid">
      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <%= link_to 'Dashboard', home_path, class: "navbar-brand"%>
        <% elsif !current_user.admin? %>
          <%= link_to 'Home', home_path, class: "navbar-brand"%>
        <% end%>
      <%else%>
        <%= link_to 'Point of Sale', home_path, class: "navbar-brand"%>
      <% end%>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'About Us', home_about_path, class: "nav-link"%>
          </li>
          <%# <li class="nav-item">
            <%= link_to 'Customers', friends_path, class: "nav-link" %>
          <%# </li> %>
          <% if !user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Sign Up',  new_user_registration_path, class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class:"btn btn-primary"%>
            </li>
          </ul>
        </div>
        <div class="flex-shrink-0 flex items-center pl-5 pr-5">
          <%= link_to root_path do %>
            <%= image_tag 'logo2.png', class: 'block lg:hidden h-10 w-auto' %>
          <% end %>
          <%= link_to root_path do %>
            <%= image_tag 'logo2.png', class: 'hidden lg:block h-10 w-auto' %>
          <% end %>
        </div>
      <% end %>
      <% if user_signed_in? %>
      </li>
      <%# <li class="nav-item">
                  <%= link_to 'Add Customer', new_friend_path, class: "nav-link"%>
      <%# </li> %>
      <li class="nav-item flex space-x-10 pl-5 pr-5">
        <%= link_to 'Sell', categories_path, class: "text-gray-500 py-2 rounded-md text-md font-medium" %>
      </li>
      <li class="nav-item">
        <div class="hidden sm:flex sml:ml-6 items-center justify-center pl-5 pr-5">
          <div class="flex space-x-10">
            <%= link_to cart_path, class: "text-gray-500 hover:underline py-2 rounded-md text-md font-medium" do %>
              <%# <%= icon 'fa-solid', 'shopping-cart' %>
              <span class = "fas fa-shopping-cart "> </span>
            <% end %>
          </div>
        </li>
        <% if current_user.manager? %>
          <li class="nav-item">
            <%= link_to 'Categories', admin_categories_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Products', admin_products_path, class: "nav-link"%>
          </li>
          <%# <li class="nav-item">
            <%= link_to 'Orders',  admin_orders_path, class: "nav-link"%>
          <%# </li> %>
        <% end %>
        <% if !current_user.admin? %>
          <li class="nav-item" style="margin-left:10px">
            <%= link_to "Profile' #{current_user.id} \u{2740}   #{current_user.email} \u{2740}", root_path, class:"nav-item btn btn-outline-info" %>
          </li>
        <% end%>
        <li  style="margin-left:10px">
          <%# <%= link_to 'Sign Out', destroy_user_session_path, method: :delete%>
          <%= button_to "Sign Out", destroy_user_session_path, :method => 'delete', data:{turbo: "false"}, class:"fas fa-sign-out-alt btn btn-primary mt-1 py-1", style: "color: #157347" %>
        </li>
        <form class="d-flex" style="margin-left:10px">
          <button class="btn btn-success"><%= link_to "Role: #{current_user.role.capitalize} \u{1F466}"%></button>
        </form>
      <% end %>
    </ul>
  </div>
</div>
</nav>
<% end %>

app/views/home/about.html.erb
<div class = "pb-40" style="background-image: url('<%= asset_path('about-background.jpg') %>'); background-size: cover;">
  <div class="container">
    <br>
    <br>
    <%= image_tag('about_me.jpg', alt: 'About Us Image',style:"max-width: 100%; hight: 200px; width:150px", class: "about_us") %>
    <h3 class="fs-3"><%= @about_me%></h3>
    <p>I am a software engineering student at Virtual Universty of Pakistan </p>
    <p>This is my Final Year Project </p>
  </div>
  <!-- Button to toggle calculator visibility -->
  <div style="display: none">
    <button id="toggleCalculator"  >Toggle Calculator</button>
    <!-- Calculator form -->
    <div id="calculator" style="<%= cookies[:calculator_open]? 'display: block;' : 'display: none;' %>">
      <h1>Calculator</h1>
      <%= form_tag(home_about_path, method: :get) do %>
        <%= label_tag(:first_number, "Enter first number:") %>
        <%= text_field_tag(:first_number, params[:first_number]) %>
        <%= label_tag(:second_number, "Enter second number:") %>
        <%= text_field_tag(:second_number, params[:second_number]) %>
        <%= submit_tag("Add") %>
        <button id="clear">Clear Fields</button>
      <% end %>
      <% if @result.present? %>
        <h2>Result: <%= @first_number %> + <%= @second_number %> = <%= @result %></h2>
        <button id="close">Close Calculator</button>
      <% end %>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
    </div>
    <%# <script>
                        // Function to toggle calculator visibility
                        document.getElementById('toggleCalculator').addEventListener('click', function() {
                            var calculator = document.getElementById('calculator');
                            if (calculator.style.display === 'none') {
                            calculator.style.display = 'block';
                            } else {
                            calculator.style.display = 'none';
                            }
                        });
                        </script> %>
    <script>
      // Function to toggle calculator visibility
      document.getElementById('toggleCalculator').addEventListener('click', function() {
          var calculator = document.getElementById('calculator');
          if (calculator.style.display === 'none') {
          calculator.style.display = 'block';
          document.cookie = "calculator_open=false;"
          } else {
          calculator.style.display = 'none';
          document.cookie = "calculator_open=true;"
          }
      });

      // Function to close calculator after seeing result
      document.getElementById('close').addEventListener('click', function() {
          var calculator = document.getElementById('calculator');
          calculator.style.display = 'none';
          document.cookie = "calculator_open=false";
      });
          // Function to clear calculator fields
      document.getElementById('clear').addEventListener('click', function() {
          document.getElementById('first_number').value = '';
          document.getElementById('second_number').value = '';
      });
    </script>

app/views/home/index.html.erb
<h1 class="fs-3" style= "padding-left:10px"> Final Year Project </h1>
<div class="bg-gray-800 text-white text-center py-20">
  <h1 class="text-5xl font-bold mb-4">Welcome to POS</h1>
  <p class="text-xl mb-8">Your one-stop shop for all your e-commerce needs!</p>
  <% if !user_signed_in? %>
    <%= link_to "Create a Company", sign_up_path, class: "bg-gray-500 hover:bg-gray-600 text-white font-bold py-2 px-4 rounded" %>
  <%end%>
</div>
<div class="jumbotron">
  <div class="card-body">
    <div class= "pb-40 mb-20" style="background-image: url('<%= asset_path('background.jpg') %>'); background-size: cover;">
      <h3 class="display-4" style="display: inline-block">
        Asghar Ali
      </h3>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
    </div>
    <hr class= "my-4">
    <p class="lead" style="display: inline-block">
      Student ID: BC200414501
      Group Id: F23028CB55 (Single)
    </p>
    <h3 class="fs-3" style="color: #612200;">
      Supervisor Name: Saima Jamil
    </h3>
  </div>
</div>
<%# <div class="flex flex-wrap justify-center mt-8 items-center gap-10">
        <% @main_categories.each do |category| %>
  <%# <%= link_to category_path(category) do %>
    <%# <div class="flex flex-col mb-4">
              <h2 class="text-gray-800 font-medium text-lg text-center mb-6"><%= category.name %></h2>
  <%# <%= category.image.present? ? image_tag(category.image, class: "max-w-lg") : image_tag("http://via.placeholder.com/512") %>
  <%# </div>
          <% end %>
  <%# <% end %>
  <%# </div> %>
  <div class="bg-gray-100 py-20 my-10">
    <div class="container mx-auto px-6">
      <h2 class="text-4xl font-bold text-center text-gray-800 mb-8">Customer Testimonials</h2>
      <div class="flex flex-wrap">
        <div class="w-full md:w-1/3 px-2 mb-4">
          <div class="bg-gray-100 rounded shadow py-4 px-4">
            <p class="text-gray-800 text-base mb-4">
              "I've been shopping on POS for years, and it's always been a fantastic experience!"
            </p>
            <p class="text-gray-500 text-xs">
              - Ahmad Ali
            </p>
          </div>
        </div>
        <div class="w-full md:w-1/3 px-2 mb-4">
          <div class="bg-gray-100 rounded shadow py-4 px-4">
            <p class="text-gray-800 text-base mb-4">
              "I've been shopping on POSfor years, and it's always been a fantastic experience!"
            </p>
            <p class="text-gray-500 text-xs">
              - Hamza Yousaf
            </p>
          </div>
        </div>
        <div class="w-full md:w-1/3 px-2 mb-4">
          <div class="bg-gray-100 rounded shadow py-4 px-4">
            <p class="text-gray-800 text-base mb-4">
              "I've been shopping on POS for years, and it's always been a fantastic experience!"
            </p>
            <p class="text-gray-500 text-xs">
              - Akbar Ali
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="bg-gray-500 text-white my-10 text-center py-20">
    <h2 class="text-3xl font-bold mb-6">Stay Updated</h2>
    <p class="mb-8">Subscribe to our newsletter for the latest updates and offers.</p>
    <%= form_with url: root_path, method: :post, local: true, class: "flex justify-center" do %>
      <%= email_field_tag :email, nil, placeholder: "Enter your email", class: "p-2 rounded-l text-gray-800" %>
      <%= submit_tag "Subscribe", class: "bg-gray-700 hover:bg-gray-800 cursor-pointer text-white font-bold py-2 px-4 rounded-r" %>
    <% end %>
  </div>