config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :orders
    
    resources :products do
      resources :stocks
    end
    resources :categories
    # root to: "admin#index"
  end
  resources :members

  # get 'members/index'
  # get 'members/create'
  # get 'members/new'
  # get 'members/edit'
  # get 'members/update'
  # get 'members/destroy'
  resources :companies
   get 'company' => 'companies#index'
  devise_for :users # , :controllers => {:registrations => "users/registrations"}
  resources :friends
  
  get 'home/index', as: :home
  get 'home/about'
  get "admin" => "admin#index"
  get "cashier" => "cashier#index"
  get "manager" => "manager#index"
  get "cart"  => "carts#show"
  #get "invoice"  => "carts#invoice"
  get "categories" => "categories#index"
  # get "category" => "category#index"
  resources :categories, only: [:show]
  resources :products, only: [:show]
  # resources :cashier do
  #   get :index, to: 'cashier#index'  # cashier_index_path
  # end

  # resources :manager do
  #   get :index, to: 'manager#index'  # manager_index_path
  # end
  devise_scope :user do
    root to: 'home#index'
    get 'devise/registrations/new', as: :sign_up
  end

  # namespace :admin do
  #   root to: "admin#index"
  # end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "home#index"
  # root "friends#index"

  # authenticated :user do
  #   root to: "admin#index", as: :admin_root
  # end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [50, 50]
    attachable.variant :medium, resize_to_limit: [250, 250]
  end

  belongs_to :user
  belongs_to :category
  has_many :stocks
  has_many :order_products
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_admin_product, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user_or_admin, only: [:edit, :update, :destroy]



  # GET /admin/products or /admin/products.json
  def index
    if params[:query].present?
      @pagy, @admin_products = pagy(Product.where("name LIKE ?", "%#{params[:query]}%"))
    else
      @pagy, @admin_products = pagy(Product.all)
    end
    
  #   @admins = User.where(role: 'admin')
  #   @cashiers = User.where(role: 'cashier')
  #   @managers = User.where(role: 'manager')
  # @cashier_p = @cashiers.sum { |cashier| cashier.products.size }
  # @manager_p = @managers.sum { |manager| manager.products.size }
  # @admin_p = @admins.sum { |admin| admin.products.size }

  # @total_p =  @cashier_p + @admin_p + @manager_p
    @admin_products = Product.all
    
  end

  # GET /admin/products/1 or /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @admin_product = current_user.products.build
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products or /admin/products.json
  def create
    # @admin_product = Product.new(admin_product_params)    
    @admin_product = current_user.products.build(admin_product_params)
    respond_to do |format|
        if @admin_product.save
          format.html { redirect_to admin_product_url(@admin_product), notice: "Product was successfully created." }
          format.json { render :show, status: :created, location: @admin_product }
          else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @admin_product.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /admin/products/1 or /admin/products/1.json
  def update
    @admin_product = Product.find(params[:id])
    if @admin_product.update(admin_product_params.reject { |k| k["images"] })
      if admin_product_params["images"]
        admin_product_params["images"].each do |image|
          @admin_product.images.attach(image)
        end
      end
      redirect_to admin_products_path, notice: "Product updated successfully"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /admin/products/1 or /admin/products/1.json
  def destroy
    # @admin_product.destroy!

    # respond_to do |format|
    #   format.html { redirect_to admin_products_url, notice: "Product was successfully destroyed." }
    #   format.json { head :no_content }
    # end

    if @admin_product.destroy

      flash[:notice] = "Category was successfully deleted."
    else
      flash[:alert] = "An error occurred while deleting the friend."
    end
    redirect_to admin_products_url




  end

  private

  def correct_user_or_admin
    @admin_product = Product.find(params[:id])
    unless  @admin_product.user == current_user || current_user.admin?
      redirect_to admin_products_path, notice: "Not authorized to edit this friend."
    end
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @admin_product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_product_params
      params.require(:product).permit(:name, :description, :price, :category_id, :user_id, :active, images: [])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def show
      @product = Product.find(params[:id])
    end
  end
  

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, admin_product]) do |form| %>
  <% if admin_product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>
      <ul>
        <% admin_product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%# <div>
    <%= form.label :name, style: "display: block" %>
  <%# <%= form.text_field :name %>
  <%# </div> %>
  <%# <div> %>
  <%# <%= form.label :description, style: "display: block" %>
  <%# <%= form.text_area :description %>
  <%# </div> %>
  <%# <div> %>
  <%# <%= form.label :price, style: "display: block" %>
  <%# <%= form.number_field :price %>
  <%# </div> %>
  <%# <div> %>
  <%# <%= form.label :category_id, style: "display: block" %>
  <%# <%= form.text_field :category_id %>
  <%# </div> %>
  <%# <div> %>
  <%# <%= form.label :active, style: "display: block" %>
  <%# <%= form.check_box :active %>
  <%# </div> %>
  <%# <div> %>
  <%# <%= form.submit %>
  <%# </div>  %>
  <div class="main-wrapper" style="display:inline-block">
    <div class="account-content">
      <div class="login-wrapper">
        <div class="login-content">
          <div class="login-userset">
            <div class="form-login" >
              <%# <%= form.label :first_name, style: "display: block" %>
              <%= form.text_field :name, rows: 4, placeholder: "Product Name" %>
              <%# <%= form.label :name, style: "display: block" %>
              <%# <%= form.text_field :name %>
            </div>
            <div class="form-login">
              <%# <%= form.label :email, style: "display: block" %>
              <%= form.text_area :description, rows: 4 , placeholder: "Description" %>
            </div>
            <div class="form-login">
              <% if admin_product.images.any? %>
                <% admin_product.images.each do |image| %>
                  <%= image_tag image, class: "w-20 h-20 object-cover rounded-md" %>
                <% end %>
              <% end %>
              <%= form.label :images %>
              <%= form.file_field :images, multiple: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
            </div>
            <div class="form-login">
              <%# <%= form.label :email, style: "display: block" %>
              <%= form.number_field :price, rows: 4 , placeholder: "Price" %>
            </div>
            <div class="form-login" >
              <%= form.label :category_id %>
              <%= form.collection_select :category_id, Category.order(:name), :id, :name, id: "category", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
            </div>
            <div class="form-login" >
              <%= form.label :active %>
              <%= form.check_box :active, class: "block mt-2 h-5 w-5" %>
            </div>
            <% unless admin_product.new_record? %>
              <div class="my-5">
                <%= link_to "Product Stocks", admin_product_stocks_path(admin_product), class: "btn btn-secondary underline" %>
              </div>
            <% end %>
            <div class="form-login">
              <%# <%= form.label :gender, style: "display: block" %>
              <%= form.number_field :user_id, id: :product_user_id, value:current_user.id, type: :hidden %>
            </div>
          </div>
        </div>
        <div class="login-img">
          <!--        <img src="assets/img/login.jpg" alt="img">-->
          <%= image_tag 'product.jpg' %>
        </div>
      </div>
      <div class= "actions" >
        <%= form.submit class: "btn btn-primary", style:"margin-left:35px; display:inline-block;" %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>">
  <%# <p>
    <strong>Name:</strong>
    <%= product.name %>
  <%# </p> %>
  <%# 
  <p>
    <strong>Description:</strong>
    <%= product.description %>
  <%# </p> %>
  <%# 
  <p>
    <strong>Price:</strong>
    <%= product.price %>
  <%# </p> %>
  <%# <p>
    <strong>Category:</strong>
    <%= product.category_id %>
  <%# </p> %>
  <%# <p>
    <strong>Active:</strong>
    <%= product.active %>
  <%# </p>  %>
  <tr>
    <td> <%= product.id %> </td>
    <%# <td><%= friend.user_id</td>  %>
    <%# <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800 underline">
      <%# <%= category.image.present? ? image_tag(category.image.variant(:thumb)) : image_tag("https://via.placeholder.com/50") %>
    <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800 underline">
      <%# <%= category.image.present? ? image_tag(category.image.variant(:thumb)) : image_tag("https://via.placeholder.com/50") %>
      <% if product.images.any? %>
        <%= image_tag(product.images.first, style: "width: 50px; height: 50px; object-fit: cover;") %>
      <% else %>
        <%= image_tag("https://via.placeholder.com/50") %>
      <% end %>
    </td>
    <%# <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800 underline">
    <%= product.images.any? ? image_tag(product.images.first, style: "width: 50px; height: 50px; object-fit: cover;") : image_tag("https://via.placeholder.com") %>
    <%# </td>  %>
    <td> <%=  link_to "#{product.name} " , [:admin, product], class: 'text-decoration-underline text-primary' %>
      <%# <%= friend.first_name %>
    </td>
    <%# <td> <%= friend.last_name</td>   %>
    <td> <%= product.description %></td>
    <td> <%= product.price %></td>
    <td> <%= product.category_id %></td>
    <% if product.user.present? %>
      <td><%= product.user.email %></td>
    <% else %>
      <td>No associated user</td>
    <% end %>
    <td> <%= product.active %></td>
  </div>

app/views/admin/products/edit.html.erb
<h1>Editing product</h1>
<%= render "form", admin_product: @admin_product %>
<br>
<div>
  <%= link_to "Show this product", [:admin, @admin_product], class:"btn btn-info" %> |
  <%= link_to "Back to products", admin_products_path, class: "btn btn-secondary" %>
</div>

app/views/admin/products/index.html.erb
<%# <p style="color: green"><%= notice</p> %>
<% if user_signed_in? %>
  <% if current_user.role != "cashier"%>
    <h1 class="fs-1">Products</h1>
    <div id="admin_products">
      <%# <% @admin_products.each do |admin_product| %>
        <%# <%= render admin_product %>
        <%# <p> %>
        <%# <%= link_to "Show this product", admin_product %>
        <%# </p> %>
        <%# <% end %>
      </div>
      <%= link_to "New product", new_admin_product_path , class:"btn btn-primary float-end"%>
      <div class="flex mt-3 flex-col md:flex-row items-start md:items-center justify-betwee w-full">
        <%= form_with url: admin_products_path, method: :get, class: "flex" do |form| %>
          <%= form.text_field :query, placeholder: "Search", class: "rounded border border-black text-gray-800"%>
          <%= form.submit "Submit", class: "cursor-pointer  ml-2 mt-1 hover:bg-orange-600 text-white py-2 px-4 rounded btn btn-success"%>
        <% end%>
        <%= form_with url: admin_products_path, method: :get, class: 'flex' do |form|%>
          <%= form.submit "Clear", class: "cursor-pointer  ml-0 md:ml-2 mt-1 md:mt-0 hover:bg-orange-600 text-white py-2 px-4 rounded btn btn-secondary"%>
        <% end%>
      </div>
      <table class="table table-striped table-hover table-bordered" >
        <thead class="table-light">
          <tr>
            <th>ID</th>
            <th>Photo <%="\u{1F468}"%> </th>
            <th>Name <%="\u{1F468}"%> </th>
            <%# <th>Last name</th> %>
            <th>Description <%="\u{2709}"%> </th>
            <th>Price <%="\u{2709}"%> </th>
            <th>Category ID <%="\u{2709}"%> </th>
            <th>Added By <%="\u{1F60E}"%> </th>
            <th>Status <%="\u{1F60E}"%> </th>
            <th>Action <%="\u{2764}"%> </th>
            <%# <% if current_user.email == "asghar@gmail.com"%>
            <th>Sr.No </th>
          </tr>
        </thead>
        <tbody>
          <div id="product">
            <%no= 0%>
            <% User.all.each do |user| %>
              <% user.products.each do |product| %>
                <%no += 1%>
                <%# <% if friend.user == current_user %>
                <%= render product %>
                <td >
                  <%# <%=  link_to "Show ", friend, class: "btn btn-outline-dark" %>
                  <%# <button   class=""></button>   %>
                  <%= button_to "Delete",[:admin, product], method: :delete, class:"btn btn-outline-danger btn-sm", onclick: 'return confirm("Are you sure?");' %>
                  <%# <%= link_to "Edit", edit_friend_path(@friend),class:"btn btn-primary",style:"margin-top:10px; margin-bottom:10px;display:inline-block;" %>
                  <%# <%= friend.user_id %>
                </td>
                <td>
                  <%=no%>
                </td>
              </tr>
              <%# <% end %>
            <% end %>
          <% end %>
          <%# <% else %>
          <%# </tr>
            </thead>
            <div id="product">
              <% @admin_products.each do |product| %>
            <%# <% if product.user == current_user %>
            <%# <%= render product %>
            <%# <td >
                    <%# <%=  link_to "Show ", friend, class: "btn btn-outline-dark" %>
            <%# <button   class=""></button>   %>
            <%# <%= button_to "Delete", [:admin, product], method: :delete, class:"btn btn-outline-danger btn-sm", onclick: 'return confirm("Are you sure?");' %>
            <%# <%= link_to "Edit", edit_friend_path(@friend),class:"btn btn-primary",style:"margin-top:10px; margin-bottom:10px;display:inline-block;" %>
            <%# <%= friend.user_id %>
            <%# </td>
                </tr>
              <% end %>
            <%# <% end %>
            <%# <% end %>
          </div>
        </tbody>
      </table>
      <%== pagy_nav(@pagy) if @pagy.pages > 1%>
    <% else %>
      <h1>You are not authorize to access this option</h1>
    <% end %>
  <% end %>

app/views/admin/products/new.html.erb
<h1>New product</h1>
<%= render "form", admin_product: @admin_product %>
<br>
<div>
  <%= link_to "Back to products", admin_products_path, class: "btn btn-secondary " , style:"margin-left:35px; display:inline-block;"%>
</div>

app/views/admin/products/show.html.erb
<%# <p style="color: green"><%= notice</p> %>
<%# <%= render @admin_product %>
<div>
  <%# <%= link_to "Edit this product", edit_admin_product_path(@admin_product) %>
  <%# <%= link_to "Back to products", admin_products_path %>
  <%# <%= button_to "Destroy this product", @admin_product, method: :delete %>
</div>
<%# <p style="color: green"><%= notice</p> %>
<div class="jumbotron">
  <div class="card-body">
    <h1 class="display-4">
      <%= @admin_product.name %>
    </h1>
    <p class="lead">
      <%= @admin_product.description %>
    </p>
    <hr class= "my-4">
    <%# <%= link_to "Edit", edit_friend_path(@friend),class:"btn btn-primary btn-lg",style:"margin-top:10px; margin-bottom:10px;display:inline-block;" %>
    <%# <a href="#" class="btn btn-primary btn-lg" role="button">Button</a> %>
  </div>
</div>
<table class="table table-striped table-hover table-bordered" >
  <thead class="table-light">
    <tr>
      <th>ID</th>
      <th>Photo <%="\u{1F468}"%> </th>
      <th>Name <%="\u{1F468}"%> </th>
      <th>Description <%="\u{2709}"%> </th>
      <th>Price <%="\u{2709}"%> </th>
      <th>category_id ID <%="\u{2709}"%> </th>
      <th>User Name <%="\u{1F60E}"%> </th>
      <th>Status <%="\u{1F60E}"%> </th>
    </tr>
  </thead>
  <%= render @admin_product %>
</tr>
</table>
<div style= "display:inline-block";>
  <%= link_to "Edit", edit_admin_product_path(@admin_product),class:"btn btn-primary",style:"margin-top:10px; margin-bottom:10px;display:inline-block;" %>
  <%= link_to "Back", admin_products_path, class:"btn btn-secondary" ,style:"margin-top:10px; margin-bottom:10px;display:inline-block;" %>
</div>
<div style= "display:inline-block";>
  <%= button_to "Delete", [:admin, @admin_product], method: :delete, class:"btn btn-danger", onclick: 'return confirm("Are you sure?");' %>
</div>
<%# <div class="card w-50">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Button</a>
  </div>
</div> %>
<br>
<br>